import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from sklearn.model_selection import StratifiedShuffleSplit
import pandas as pd
from common_holdout import (
    load_labels,
    make_binary_labels,
    apply_multiclass_policy,
    save_json,
    save_binary_counts,
    save_multiclass_counts,
)

# labeled_nodes_in_graph.csv is the graph-matched label file: it has node_id (integer graph ID),
# address, name_normalized, entity, category. It is generated by check_label_coverage.py from
# stellar_directory_normalized.csv + the graph. We use name_normalized as the label column
# because that is what SSLPA uses as seeds ("SCAM" for malicious nodes).
# stellar_directory_normalized.csv cannot be used directly here because it has no node_id column.
LABELS_CSV = "/home/user/jfayzullaev/stellar-clustering/publication/new-labled-data/normalization/labeled_nodes_in_graph.csv"
OUT = Path(__file__).parent / "step6_holdout" / "fixed_test"
OUT.mkdir(parents=True, exist_ok=True)

TEST_RATIO = 0.20
RANDOM_SEED = 42
MIN_CLASS_SIZE = 10

df = load_labels(LABELS_CSV)

# Binary
df_bin = make_binary_labels(df)

sss_bin = StratifiedShuffleSplit(n_splits=1, test_size=TEST_RATIO, random_state=RANDOM_SEED)
dev_idx_b, test_idx_b = next(sss_bin.split(df_bin[["node_id"]], df_bin["binary_label"]))

dev_bin = df_bin.iloc[dev_idx_b].copy()
test_bin = df_bin.iloc[test_idx_b].copy()

membership_bin = pd.concat([
    dev_bin[["node_id", "binary_label"]].assign(split_role="development"),
    test_bin[["node_id", "binary_label"]].assign(split_role="test"),
], ignore_index=True)
membership_bin.to_csv(OUT / "fixed_test_membership_binary.csv", index=False)

save_binary_counts(dev_bin, "fixed_test", "development", OUT / "fixed_test_binary_counts.csv")
save_binary_counts(test_bin, "fixed_test", "test", OUT / "fixed_test_binary_counts.csv")

dev_bin[["node_id", "binary_label"]].rename(columns={"binary_label": "label"}).to_csv(
    OUT / "fixed_dev_labels_binary.csv", index=False
)
test_bin[["node_id", "binary_label"]].rename(columns={"binary_label": "label"}).to_csv(
    OUT / "fixed_test_labels_binary.csv", index=False
)

# Multiclass
df_mul, keep_classes, merged_classes = apply_multiclass_policy(df, min_class_size=MIN_CLASS_SIZE)

sss_mul = StratifiedShuffleSplit(n_splits=1, test_size=TEST_RATIO, random_state=RANDOM_SEED)
dev_idx_m, test_idx_m = next(sss_mul.split(df_mul[["node_id"]], df_mul["multiclass_label"]))

dev_mul = df_mul.iloc[dev_idx_m].copy()
test_mul = df_mul.iloc[test_idx_m].copy()

membership_mul = pd.concat([
    dev_mul[["node_id", "multiclass_label"]].assign(split_role="development"),
    test_mul[["node_id", "multiclass_label"]].assign(split_role="test"),
], ignore_index=True)
membership_mul.to_csv(OUT / "fixed_test_membership_multiclass.csv", index=False)

save_multiclass_counts(dev_mul, "fixed_test", "development", OUT / "fixed_test_multiclass_counts.csv")
save_multiclass_counts(test_mul, "fixed_test", "test", OUT / "fixed_test_multiclass_counts.csv")

dev_mul[["node_id", "multiclass_label"]].rename(columns={"multiclass_label": "label"}).to_csv(
    OUT / "fixed_dev_labels_multiclass.csv", index=False
)
test_mul[["node_id", "multiclass_label"]].rename(columns={"multiclass_label": "label"}).to_csv(
    OUT / "fixed_test_labels_multiclass.csv", index=False
)

save_json(OUT / "fixed_test_config.json", {
    "random_seed": RANDOM_SEED,
    "test_ratio": TEST_RATIO,
    "development_ratio": 1.0 - TEST_RATIO,
    "multiclass_min_class_size": MIN_CLASS_SIZE,
    "multiclass_kept_classes": keep_classes,
    "multiclass_merged_to_OTHER": merged_classes,
})

print("Done: fixed test split created.")